<div class="content row">
    <section class="col-lg-12 col-lg-offset-2">
        <header class="clearfix">
            
                     <div class="navbar navbar-inverse navbar-fixed-top">
                         <div class="container">
                                    <a class="navbar-brand" href="index.php">Patrick McDonough</a>

                                    <ul class="nav navbar-nav">
                                        <li class="active"><a href="#about">About Me</a></li>
                                            <li class="hidden-phone"><a class="transition" href="#skills">Skills</a></li>
                                            <li><a href="#contactMe">Contact</a></li>
                                            <li class="hidden-phone"><a href="#samples">Portfolio</a></li>
                                            <li class="hidden-phone"><a href="#webGallery">Web Gallery</a></li>
                                    </ul>
                              </div>
                        </div>
            
         </header>
       
    </section>
 </div>
   
