 <article class="transition portfolio" id="samples">
        <div class="row">
            <div class="col-lg-12  col-lg-offset-0">
                <h3 class="articleTitle">Portfolio</h3>
            </div>
        </div>
     
     <!--CORPORATE-->
        <div class="row">
            <div class=" hidden-phone  hidden-xs col-lg-3 col-md-4 col-sm-2 col-sm-offset-1 col-lg-offset-2 col-md-offset-1 ">

                <h4>Corporate ID</h4>
                <p class="portfolio">Creating corporate ID is one of the most rewarding things I do. 
                    I enjoy taking the clients vision and bringing it to 
                    fruition. I use Illustrator and Photoshop to 
                    create and deliver beautiful and effective logos. </p>

            </div>
            <div class="col-lg-5 col-lg-offset-1 col-sm-4 col-xs-3 col-sm-offset-2 hidden-phone">
                <div id="myCarousel_ID" class="carousel slide">
                    <!-- Carousel items -->
                    <div class="carousel-inner ">
                        <div class="active item"><img alt="bamboo teak logo design" src="img/bamboo_03.png">
                            <div class="carousel-caption">
                                <h4>Bamboo Teak</h4>
                                <p>Specialty clothing company</p>
                            </div>
                        </div>
                        <div class="item"><img alt="sample logo" src="img/chiro_03.png">
                            <div class="carousel-caption">
                                <h4>Chiropractic Office</h4>
                                <p>Medical and Pharmaceutical</p>
                            </div>
                        </div>
                        <div class="item"><img alt="World Cuisine Logo Design" src="img/world-cuisine_03.png">
                            <div class="carousel-caption">
                                <h4>World Cuisine</h4>
                                <p>Importer of culinary equipment. Los Angeles, CA</p>
                            </div>
                        </div>
                        <div class="item"><img alt="Smile Wrap Logo Design" src="img/smile_03.png">
                            <div class="carousel-caption">
                                <h4>Smile Wrap</h4>
                                <p>Personal hygiene retail</p>
                            </div>
                        </div>
                    </div>
                    <!--Carousel nav -->
                    <a class="carousel-control left" href="#myCarousel_ID" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
                    <a class="carousel-control right" href="#myCarousel_ID" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
                </div>
            </div>

        </div>
    </article>


<!--WEB DEVELOPMENT-->


    <article class="transition">
   
        <div class="row">

            <div class=" hidden-phone  hidden-xs col-lg-3 col-md-4 col-sm-2 col-sm-offset-1 col-lg-offset-2 col-md-offset-1 ">
                <h4>Web Development</h4>
                <p class="portfolio">My philosophy on web development is to listen very carefully to the project sponsor and deliver the project as quickly as possible 
                    exceeding their expectations. I do this by immerse myself in new technology to learn as much as possible about my craft. 
                </p>
                <p class="portfolio">I have been developing web sites since the days of AOL and dial-up. I have coded in ColdFusion, 
                    php, python, html5 and flash. I have created static sites, dynamic sites, CMS, eCommerce and 
                    much much more. </p>
            </div>
            <div class="col-lg-5 col-lg-offset-1 col-sm-4 col-xs-3 col-sm-offset-2 hidden-phone">
                <div id="myCarousel_web" class="carousel slide">
                     <!--Carousel items -->
                    <div class="carousel-inner">
                        <div class="active item"><img alt="Web sample Headhunters NW" src="img/headhunters_03.jpg"> 
                            <div class="carousel-caption">
                                <h4>Headhunters NW</h4>
                                <p>Joomla site for recruiter</p>
                            </div>
                        </div>
                        <div class="item"><img alt="Archery sports website" src="img/archery_03.png"> 
                            <div class="carousel-caption">
                                <h4>Archery Sports USA</h4>
                                <p>eCommerce using grfxsStore ColdFusion framework</p>
                            </div>
                        </div>
                        <div class="item"><img alt="Key Publishing Website Sample" src="img/KPG_03.jpg"> 
                            <div class="carousel-caption">
                                <h4>Key Publishing Group</h4>
                                <p>Corporate site in HTML5, CSS3, PHP </p>
                                <p><small>Design by Kyle Shold</small></p>
                            </div>
                        </div>
                        <div class="item"><img alt="Petco Park Campaign" src="img/petcopark_03.jpg"> 
                            <div class="carousel-caption">
                                <h4>Petco Park</h4>
                                <p>RIA to customize and purchase commemorative book</p>
                            </div>
                        </div>
                        <div class="item"><img alt="Northcoast Sample Website" src="img/northcoast_03.jpg"> 
                            <div class="carousel-caption">
                                <h4>North Coast Lodge</h4>
                                <p>Wordpress with reservation plug-in</p>
                            </div>
                        </div>
                        <div class="item"><img alt="IMATS trade show website" src="img/imats_03.jpg"> 
                            <div class="carousel-caption">
                                <h4>IMATS</h4>
                                <p>CMS in PHP. Upgrades and maintenance</p>
                            </div>
                        </div>

                    </div>
<!-- Carousel nav -->
                    <a class="carousel-control left" href="#myCarousel_web" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
                    <a class="carousel-control right" href="#myCarousel_web" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
                </div>

            </div>
        </div>
    </article>


<!-- PRINT-->


<article class="transition">
        <div class="row">
            <div class="  hidden-phone  hidden-xs col-lg-3 col-md-4 col-sm-2  col-sm-offset-1 col-lg-offset-2 col-md-offset-1">
                <h4>Print</h4>
                <p class="portfolio">I've produced lots of great printed deliverables including program books for the Golden Globes and Comedy Awards. I've been involved in thousands of print projects as a photo assistant to a creative director. </p>
            </div>
      
            <div class="col-lg-5 col-lg-offset-1 col-sm-4 col-xs-3 col-sm-offset-2 2hidden-phone">
                <div id="myCarousel_print" class="carousel slide" data-ride="carousel">
<!--                     Carousel items -->
                    <div class="carousel-inner">
                        <div class="active item"><img alt="World Cuisine Catalog Sample" src="img/worldcuisineCat_03.jpg"> 
                            <div class="carousel-caption">
                                <h4>World Cuisine</h4>
                                <p>120 Page printed catalog</p>
                            </div>
                        </div>
                        <div class="item"><img alt="Golden Globes Program Book" src="img/goldenglobesProg_03.jpg"> 
                            <div class="carousel-caption">
                                <h4>Golden Globes</h4>
                                <p>Event program for annual television show</p>
                                <p><small>Art Direction by Sal Scorza</small></p>
                            </div>
                        </div>
                        <div class="item"><img alt="Comedy Awards Program Book" src="img/11thACA_03.jpg"> 
                            <div class="carousel-caption">
                                <h4>11th Annual American Comedy Awards</h4>
                                <p>Event program for annual television show</p>
                                <p><small>Client: George Schlatter</small></p>
                            </div>
                        </div>
                    </div>
<!-- Carousel nav -->
                    <a class="carousel-control left" href="#myCarousel_print" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
                    <a class="carousel-control right" href="#myCarousel_print" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
                </div>
            </div>
              </div>
    </article>