<article class="row  transition hidden-md" id="skills">

        <div class="col hidden-md hidden-lg ">
            <h3 class="articleTitle">Skills</h3>
        </div>

        <div id="oldStyleSkills" class="col hidden-md hidden-lg">

            <div class="col-sm-2">
                    <dl>
                        <dt><span>Project Management</dt>
                        <dd> Scope Management</dd>
                        <dd> Planning</dd>
                        <dd> Monitoring</dd>
                        <dd> Testing</dd>
                        <dd> Work Breakdown Schedule</dd>
                        <dd> Waterfall, Agile and Lean</dd>
                    </dl>
        </div>
             <div class="col-sm-2">
                    <dl>
                        <dt>Design</dt>
                        <dd> Graphic Design</dd>
                        <dd> Web Design</dd>
                        <dd> UX/UI</dd>
                        <dd> Photo Processing</dd>
                        <dd> Wireframe</dd>
                        <dd> High Definition Internet Prototyping</dd>
                    </dl>
             </div>
                  <div class="col-sm-2">
                      <dl>
                                   <dt>Programming</dt>
                                    <dd>HTML</dd>
                                    <dd>HTML5</dd>
                                    <dd>XHTML</dd>
      
                                    <dd>PHP<dd>
                                    <dd>SQL</dd>
                                    <dd>Web Services</dd>
                                    <dd>SOAP</dd>
                               
                                    <dd>CSS</dd>
                                    <dd>CSS3</dd>
                                    <dd>Twitter Bootstrap</dd>
                                    <dd>SaSS</dd>
                               
                                    <dd>Java-script</dd>
                                    <dd>JQuery</dd>
                                    <dd>Actionscript</dd>
                                    <dd>AngularJS</dd>
                                
                                    <dd>Joomla</dd>
                                    <dd>Drupal</dd>
                                    <dd>Wordpress</dd>
                    </dl>
                   
                  </div>
                         <div class="col-sm-2">
                    <dt>Marketing</dt>
                        <dd> Optimization SEO</dd>
                        <dd> Social Media</dd>
                        <dd> Email Marketing</dd>
                        <dd> PPC</dd>

                    </dl>
                    <br>
                    <dl>
                    <dt>IT</dt>
                        <dd> LAN Deployment and Administration</dd>
                        <dd> Windows Server 2008</dd>
                        <dd> Domain Deployment and Administration</dd>
                        <dd> Multi Platform </dd>
                    </dl>
</div>
                </div>


    </article>