<article class="row  transition" id="skills">

        <div class="col col-lg-2 col-md-offset-0 col-sm-2 col-sm-offset-0 hidden-phone  hidden-xs">
            <h3 class="articleTitle">Skills</h3>
        </div>

        <div id="oldStyleSkills" class="col tabbed_content hidden-phone col-sm-10 hidden-xs col-lg-8 col-md-6 col-lg-offset-0 col-md-offset-0 col-sm-offset-1">

            <div class='tabs'>
                <div class='moving_bg'>
                    &nbsp;
                </div>
                <span class='tab_item'>Project Management</span>
                <span class='tab_item'>Design</span>
                <span class='tab_item'>Development</span>
                <span class='tab_item'>Internet Marketing</span>
                <span class='tab_item'>IT</span>
            </div>

            <div class='slide_content'>
                <div class='tabslider'>

                    <ul>
                        <li><i class=" icon-check icon-white"></i>Scope Management</li>
                        <li><i class=" icon-check icon-white"></i>Planning</li>
                        <li><i class=" icon-check icon-white"></i>Monitoring</li>
                        <li><i class=" icon-check icon-white"></i>Testing</li>
                        <li><i class=" icon-check icon-white"></i>Work Breakdown Schedule</li>
                        <li><i class=" icon-check icon-white"></i>Waterfall, Agile and Lean</li>
                    </ul>

                    <ul>
                        <li><i class=" icon-check icon-white"></i>Graphic Design</li>
                        <li><i class=" icon-check icon-white"></i>Web Design</li>
                        <li><i class=" icon-check icon-white"></i>UX/UI</li>
                        <li><i class=" icon-check icon-white"></i>Photo Processing</li>
                        <li><i class=" icon-check icon-white"></i>Wireframe</li>
                        <li><i class=" icon-check icon-white"></i>High Definition Internet Prototyping</li>
                    </ul>
                    <ul id="description">
                        <li>
                            <table class="table table-condensed" style="width: 85%">
                                <tr>
                                    <td>HTML</td>
                                    <td>HTML5</td>
                                    <td>XHTML</td>
                                    <td>&nbsp;</td>
                                </tr>
                                <tr>
                                    <td>PHP<a href="http://www.refsnesdata.no/certification/w3certified.asp?id=5155312">
                                            <img alt="w3C certification" src="/img/w3cert.png" width="50" ></a>"</td>
                                    <td>SQL</td>
                                    <td>Web Services</td>
                                    <td>SOAP</td>
                                </tr>
                                <tr>
                                    <td>CSS</td>
                                    <td>CSS3</td>
                                    <td>Twitter Bootstrap</td>
                                    <td>SaSS</td>
                                </tr>
                                <tr>
                                    <td>Java-script</td>
                                    <td>JQuery</td>
                                    <td>Actionscript</td>
                                    <td>AngularJS</td>
                                </tr>
                                <tr>
                                    <td>Joomla</td>
                                    <td>Drupal</td>
                                    <td>Wordpress;</td>
                                    <td>&nbsp;</td>
                                </tr>
                            </table>
                        </li>

                    </ul>
                    <ul>
                        <li><i class=" icon-check icon-white"></i>Optimization SEO</li>
                        <li><i class=" icon-check icon-white"></i>Social Media</li>
                        <li><i class=" icon-check icon-white"></i>Email Marketing</li>
                        <li><i class=" icon-check icon-white"></i>PPC</li>

                    </ul>
                    <ul>
                        <li><i class=" icon-check icon-white"></i>LAN Deployment and Administration</li>
                        <li><i class=" icon-check icon-white"></i>Windows Server 2008</li>
                        <li><i class=" icon-check icon-white"></i>Domain Deployment and Administration</li>
                        <li><i class=" icon-check icon-white"></i>Multi Platform </li>
                    </ul>

                </div>

            </div>  
        </div>


    </article>