<!--<header class="col-md-12">-->
    
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
     <div class="navbar-inner">
                    <a class="btn-default navbar-btn" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </a>
         <div class="navbar-collapse">
           <ul class="navbar-nav">
                    <li class="active"><a>About Me</a></li>
                    <li class="hidden-phone"><a class="transition" href="#skills">Skills</a></li>
                    <li><a href="#contactMe">Contact</a></li>
                    <li class="hidden-phone"><a href="#samples">Portfolio</a></li>
                    <li class="hidden-phone"><a href="#webGallery">Web Gallery</a></li>
            </ul>
    </nav>
        <h2 id="name" class="col-md-4 pull-left">Patrick McDonough</h2>
        <h3 class="col-md-7 pull-right">Tenacious Web Developer<br>Project Manager</h3>
        </div>
             
<!--     </header>-->
