<header class="span12">
    <div class="row-fluid">
        <h2 id="name" class="span5 pull-left">Patrick McDonough</h2>
        <h3 class="span7 pull-right">Tenacious Web Developer<br>Project Manager</h3>
    </div> 
             <nav class="navbar navbar-inverse">
        	<div class="navbar-inner">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </a>
                    <div class="nav-collapse">
                            <ul class="nav">
                                    <li class="active"><a>About Me</a></li>
                                    <li class="hidden-phone"><a class="transition" href="#skills">Skills</a></li>
                                    <li><a href="#contactMe">Contact</a></li>
                                    <li class="hidden-phone"><a href="#samples">Portfolio</a></li>
                                    <li class="hidden-phone"><a href="#webGallery">Web Gallery</a></li>
                            </ul>
                      </div>
              </div>
	   </nav>    
     </header>
