<script src="http://code.jquery.com/jquery-latest.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.21/angular.min.js"></script>
<script src="js/sampleSites.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.0rc1/angular-route.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.7/angular-resource.min.js"></script>
<!--<script src="js/bootstrap.js"></script>-->
<script type="text/javascript" src="http://use.typekit.com/thg3ssc.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
<!--<script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js'></script>-->
<script src="js/tabbedContent.js" type="text/javascript"></script>
<script type="text/javascript" src="js/custom.js"></script>
